/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIAsesor;

import Negocios.Asesor;
import Negocios.Seccion;
import Negocios.SeccionDAO;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/**
 *
 * @author Cristhian Ubaldo Promotor
 */
public class ConsultarMisGrupos extends javax.swing.JFrame {
    private Asesor asesor;
    ArrayList<Seccion> misSecciones;
    /**
     * Creates new form ConsultarMisGrupos
     */
    public ConsultarMisGrupos(Asesor asesor) {
        this.asesor = asesor;
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        SeccionDAO secciones = new SeccionDAO();
        
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Recursos/fondo-menu-pantalla.jpg"));
        ImageIcon icono = new ImageIcon(imagen.getImage().getScaledInstance(fondoConsultarGrupos.getWidth(), fondoConsultarGrupos.getHeight(), Image.SCALE_DEFAULT));
        fondoConsultarGrupos.setIcon(icono);
        misSecciones = secciones.obtenerSeccione(asesor.getNumeroPersonal());
        
        crearCuadrosSecciones(misSecciones);
        
    }
    
    public void crearCuadrosSecciones(ArrayList<Seccion> misSecciones){
        
        ArrayList <CuadroSeccion> cuadros = new ArrayList();
        
        for(int i = 0; i < misSecciones.size(); i++){
            
            CuadroSeccion cuadro = new CuadroSeccion(misSecciones.get(i),panelAlumnos);
            cuadros.add(cuadro);
        }
    
        mostrarCuadrosSeccion(cuadros);
    }
    
    
    public void mostrarCuadrosSeccion(ArrayList<CuadroSeccion> cuadros){
        
        int x = 5;
        int y = 5;
        
        CuadroSeccion cuadro;
        
        for(int i=0; i < cuadros.size();i++){
            
            cuadro = cuadros.get(i);
            cuadro.setBounds(x, y, 187, 134);
            panelCursos.add(cuadro);
            y += 144;
        }
            
        
        panelCursos.repaint();
        panelCursos.revalidate();
        repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JButton();
        campoBusqueda = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        cursos = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        alumnos = new javax.swing.JLabel();
        indicacionBusqueda = new javax.swing.JLabel();
        panelCursos = new javax.swing.JPanel();
        panelAlumnos = new javax.swing.JPanel();
        fondoConsultarGrupos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar grupos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setText("Regresar");
        regresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        regresar.setContentAreaFilled(false);
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 31, 90, 30));

        campoBusqueda.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        campoBusqueda.setText("Ingrese nombre o matricula");
        campoBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoBusquedaMouseClicked(evt);
            }
        });
        campoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBusquedaActionPerformed(evt);
            }
        });
        campoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBusquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBusquedaKeyTyped(evt);
            }
        });
        getContentPane().add(campoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 190, 30));

        buscar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setText("Buscar");
        buscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        buscar.setContentAreaFilled(false);
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 80, 30));

        cursos.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        cursos.setForeground(new java.awt.Color(255, 255, 255));
        cursos.setText("Cursos");
        getContentPane().add(cursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        cancelar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setText("Cancelar búsqueda");
        cancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        cancelar.setContentAreaFilled(false);
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 160, 30));

        alumnos.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        alumnos.setForeground(new java.awt.Color(255, 255, 255));
        alumnos.setText("Alumnos");
        getContentPane().add(alumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        indicacionBusqueda.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        indicacionBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        indicacionBusqueda.setText("Buscar:");
        getContentPane().add(indicacionBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 30, 60, 30));

        panelCursos.setBackground(new java.awt.Color(255, 255, 255));
        panelCursos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        panelCursos.setOpaque(false);
        getContentPane().add(panelCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, 540));

        panelAlumnos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        panelAlumnos.setOpaque(false);
        getContentPane().add(panelAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 710, 540));

        fondoConsultarGrupos.setBackground(new java.awt.Color(153, 153, 255));
        fondoConsultarGrupos.setOpaque(true);
        getContentPane().add(fondoConsultarGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        MenuPrincipalAsesor menu = new MenuPrincipalAsesor(asesor);
        dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        
       panelCursos.removeAll();
       panelAlumnos.removeAll();
       crearCuadrosSecciones(misSecciones);
        
    }//GEN-LAST:event_cancelarActionPerformed

    private void campoBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoBusquedaMouseClicked
        // TODO add your handling code here:
        campoBusqueda.setText("");
    }//GEN-LAST:event_campoBusquedaMouseClicked

    private void campoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBusquedaActionPerformed

    private void campoBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBusquedaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoBusquedaKeyTyped

    private void campoBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBusquedaKeyPressed
        
    }//GEN-LAST:event_campoBusquedaKeyPressed

    private void campoBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBusquedaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoBusquedaKeyReleased

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
       panelCursos.removeAll();
       panelAlumnos.removeAll();
       repaint();
    }//GEN-LAST:event_buscarActionPerformed

   
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alumnos;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel cursos;
    private javax.swing.JLabel fondoConsultarGrupos;
    private javax.swing.JLabel indicacionBusqueda;
    private javax.swing.JPanel panelAlumnos;
    private javax.swing.JPanel panelCursos;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
