/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIAsesor;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/**
 *
 * @author Cristhian Ubaldo Promotor
 */
public class ConsultarMisGrupos extends javax.swing.JFrame {
    private String usuario;
    /**
     * Creates new form ConsultarMisGrupos
     */
    public ConsultarMisGrupos(String usuario) {
        this.usuario = usuario;
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JButton();
        campoBusqueda = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        panelCursos = new javax.swing.JScrollPane();
        cursos = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        alumnos = new javax.swing.JLabel();
        panelAlumnos = new javax.swing.JScrollPane();
        indicacionBusqueda = new javax.swing.JLabel();
        fondoConsultarGrupos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar grupos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, -1, -1));

        campoBusqueda.setText("Ingrese nombre o matricula");
        campoBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoBusquedaMouseClicked(evt);
            }
        });
        campoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBusquedaActionPerformed(evt);
            }
        });
        campoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBusquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBusquedaKeyTyped(evt);
            }
        });
        getContentPane().add(campoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 190, 30));

        buscar.setText("Buscar");
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));
        getContentPane().add(panelCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 520));

        cursos.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        cursos.setText("Cursos");
        getContentPane().add(cursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        cancelar.setText("Cancelar búsqueda");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        alumnos.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        alumnos.setText("Alumnos");
        getContentPane().add(alumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));
        getContentPane().add(panelAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 730, 520));

        indicacionBusqueda.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        indicacionBusqueda.setText("Buscar:");
        getContentPane().add(indicacionBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        fondoConsultarGrupos.setBackground(new java.awt.Color(255, 255, 255));
        fondoConsultarGrupos.setOpaque(true);
        getContentPane().add(fondoConsultarGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void campoBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoBusquedaMouseClicked
        // TODO add your handling code here:
        campoBusqueda.setText("");
    }//GEN-LAST:event_campoBusquedaMouseClicked

    private void campoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBusquedaActionPerformed

    private void campoBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBusquedaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoBusquedaKeyTyped

    private void campoBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBusquedaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoBusquedaKeyPressed

    private void campoBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBusquedaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoBusquedaKeyReleased

   
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alumnos;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel cursos;
    private javax.swing.JLabel fondoConsultarGrupos;
    private javax.swing.JLabel indicacionBusqueda;
    private javax.swing.JScrollPane panelAlumnos;
    private javax.swing.JScrollPane panelCursos;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
