/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIAsesor;

import Negocios.UsuarioAutonomo;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Cristhian Ubaldo Promotor
 */
public class CuadroAlumno extends javax.swing.JPanel {

    /**
     * Creates new form CuadroAlumno
     * @param alumno
     */
    public CuadroAlumno(UsuarioAutonomo alumno) {
        initComponents();
        
        datosAlumno.setText(alumno.getNombre() +"\n"+alumno.getApellidos() +"\n"+alumno.getCorreo() );
        
        if(alumno.getGenero().equals("Masculino")){
            fotoGenero.setIcon(colocarImagenesEnEtiquetas("/Recursos/iconoHombre.jpg"));
        }else{
            fotoGenero.setIcon(colocarImagenesEnEtiquetas("/Recursos/iconoMujer.jpg"));
        }
        
        
    }
    
    public ImageIcon colocarImagenesEnEtiquetas(String urlImagen){
        ImageIcon imagen = new ImageIcon(getClass().getResource(urlImagen));
        ImageIcon icono = new ImageIcon(imagen.getImage().getScaledInstance(110,120 ,Image.SCALE_DEFAULT));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datosAlumno = new javax.swing.JTextArea();
        fotoGenero = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datosAlumno.setColumns(20);
        datosAlumno.setRows(5);
        add(datosAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 179, 138));
        add(fotoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 110, 120));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea datosAlumno;
    private javax.swing.JLabel fotoGenero;
    // End of variables declaration//GEN-END:variables
}
