/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Ozuna
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesionn
     */
    public IniciarSesion() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIniciarSesion = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        separadorContrasena = new javax.swing.JSeparator();
        SeparadorUsuario = new javax.swing.JSeparator();
        campoContrasena = new javax.swing.JPasswordField();
        campoUsuario = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        campoPresentacion = new javax.swing.JLabel();
        botonIngresar = new javax.swing.JButton();
        panelIngresar = new javax.swing.JPanel();
        separadorCancelar = new javax.swing.JSeparator();
        PanelPresentacion = new javax.swing.JPanel();
        EscudoUV = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        UV = new javax.swing.JLabel();
        Separador = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 470));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIniciarSesion.setBackground(new java.awt.Color(0, 102, 153));
        PanelIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelIniciarSesionMouseClicked(evt);
            }
        });
        PanelIniciarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Usuario");
        PanelIniciarSesion.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        Contraseña.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Contraseña.setText("Contraseña");
        PanelIniciarSesion.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        separadorContrasena.setForeground(new java.awt.Color(255, 255, 255));
        PanelIniciarSesion.add(separadorContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 270, 10));

        SeparadorUsuario.setForeground(new java.awt.Color(255, 255, 255));
        PanelIniciarSesion.add(SeparadorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 270, 10));

        campoContrasena.setBackground(new java.awt.Color(0, 102, 153));
        campoContrasena.setForeground(new java.awt.Color(255, 255, 255));
        campoContrasena.setText("jPasswordField1");
        campoContrasena.setBorder(null);
        campoContrasena.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        campoContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoContrasenaFocusGained(evt);
            }
        });
        campoContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoContrasenaMouseClicked(evt);
            }
        });
        campoContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContrasenaActionPerformed(evt);
            }
        });
        PanelIniciarSesion.add(campoContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 270, -1));

        campoUsuario.setBackground(new java.awt.Color(0, 102, 153));
        campoUsuario.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        campoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        campoUsuario.setText("Ingresa tu usuario");
        campoUsuario.setBorder(null);
        campoUsuario.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        campoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoUsuarioFocusGained(evt);
            }
        });
        campoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoUsuarioMouseClicked(evt);
            }
        });
        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });
        PanelIniciarSesion.add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 270, -1));

        botonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        botonCancelar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelar.setText("Cancelar");
        botonCancelar.setBorder(null);
        botonCancelar.setBorderPainted(false);
        botonCancelar.setContentAreaFilled(false);
        botonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCancelar.setPreferredSize(new java.awt.Dimension(77, 23));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        PanelIniciarSesion.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 110, 40));

        campoPresentacion.setBackground(new java.awt.Color(255, 255, 255));
        campoPresentacion.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        campoPresentacion.setForeground(new java.awt.Color(255, 255, 255));
        campoPresentacion.setText("Inicia Sesión en el portal");
        PanelIniciarSesion.add(campoPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 210, -1));

        botonIngresar.setBackground(new java.awt.Color(255, 255, 255));
        botonIngresar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        botonIngresar.setText("Ingresar");
        botonIngresar.setBorder(null);
        botonIngresar.setBorderPainted(false);
        botonIngresar.setContentAreaFilled(false);
        botonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        PanelIniciarSesion.add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 120, 40));

        panelIngresar.setBackground(new java.awt.Color(1, 80, 160));

        javax.swing.GroupLayout panelIngresarLayout = new javax.swing.GroupLayout(panelIngresar);
        panelIngresar.setLayout(panelIngresarLayout);
        panelIngresarLayout.setHorizontalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelIngresarLayout.setVerticalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        PanelIniciarSesion.add(panelIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 120, 40));

        separadorCancelar.setForeground(new java.awt.Color(255, 255, 255));
        PanelIniciarSesion.add(separadorCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 80, 10));

        getContentPane().add(PanelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 350, 470));

        PanelPresentacion.setBackground(new java.awt.Color(12, 114, 45));
        PanelPresentacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EscudoUV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Flor1024x768SinFondo.png"))); // NOI18N
        PanelPresentacion.add(EscudoUV, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 120, 350, 310));

        Titulo.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Cento de Autoacceso");
        PanelPresentacion.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 40));

        Titulo2.setBackground(new java.awt.Color(255, 255, 255));
        Titulo2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(255, 255, 255));
        Titulo2.setText("USBI Xalapa");
        PanelPresentacion.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        UV.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        UV.setForeground(new java.awt.Color(255, 255, 255));
        UV.setText("U n i v e r s i d a d  V e r a c r u z a n a");
        PanelPresentacion.add(UV, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 250, -1));

        Separador.setForeground(new java.awt.Color(255, 255, 255));
        PanelPresentacion.add(Separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 300, 10));

        getContentPane().add(PanelPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoContrasenaFocusGained
        // TODO add your handling code here:
        campoContrasena.setText("");
    }//GEN-LAST:event_campoContrasenaFocusGained

    private void campoContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoContrasenaMouseClicked
        // TODO add your handling code here:
        campoContrasena.setText("");
    }//GEN-LAST:event_campoContrasenaMouseClicked

    private void campoContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContrasenaActionPerformed

    private void campoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuarioFocusGained
        // TODO add your handling code here:
        campoUsuario.setText("");
    }//GEN-LAST:event_campoUsuarioFocusGained

    private void campoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoUsuarioMouseClicked
        // TODO add your handling code here:
        campoUsuario.setText("");
    }//GEN-LAST:event_campoUsuarioMouseClicked

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void PanelIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelIniciarSesionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelIniciarSesionMouseClicked

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel EscudoUV;
    private javax.swing.JPanel PanelIniciarSesion;
    private javax.swing.JPanel PanelPresentacion;
    private javax.swing.JSeparator Separador;
    private javax.swing.JSeparator SeparadorUsuario;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel UV;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JPasswordField campoContrasena;
    private javax.swing.JLabel campoPresentacion;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JPanel panelIngresar;
    private javax.swing.JSeparator separadorCancelar;
    private javax.swing.JSeparator separadorContrasena;
    // End of variables declaration//GEN-END:variables
}
