
package Recursos;

/**
 *
 * @author Ozuna
 */
public enum MensajeBandera {
    CONEXION_EXITOSA, ERROR_CONEXION, USUARIO_VALIDO, USUARIO_INVALIDO, ERROR_DRIVER, ERROR_CERRAR_CONEXION, CONEXION_CERRADA, USUARIO_RECEPCIONISTA,
    USUARIO_COORDINADOR, USUARIO_ASESOR, USUARIO_USUARIO_AUTONOMO, RESERVACION_EXITOSA, RESERVACION_FALLIDA;
}
